# Generated by Django 5.1.1 on 2024-10-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='deck',
            field=models.CharField(default='test', max_length=20),
            preserve_default=False,
        ),
    ]
