# Generated by Django 5.1.7 on 2025-04-18 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_customuser_phone_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bunpo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jlpt_level', models.CharField(choices=[('n5', 'N5'), ('n4', 'N4'), ('n3', 'N3'), ('n2', 'N2'), ('n1', 'N1')], max_length=2)),
                ('question', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ClearedGrammar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bunpo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bunpo')),
                ('progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cleared_grammar', to='api.userprogress')),
            ],
            options={
                'unique_together': {('progress', 'bunpo')},
            },
        ),
    ]
