# Generated by Django 5.1.7 on 2025-04-18 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_bunpo_clearedgrammar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunpo',
            name='jlpt_level',
            field=models.CharField(max_length=2),
        ),
    ]
