# Generated by Django 5.1.7 on 2025-04-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_bunpo_jlpt_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunpo',
            name='correct',
            field=models.CharField(default='correct answer', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bunpo',
            name='options',
            field=models.JSONField(default='correct answer'),
            preserve_default=False,
        ),
    ]
