# Generated by Django 5.1.7 on 2025-04-18 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_bunpo_correct_bunpo_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClearedGrammar',
            new_name='ClearedBunpo',
        ),
    ]
